Feature prepare for release
ritwik-deshpande/CustomImageBuilder pull request #5
Opened 2023-10-09 17:01 UTC by ritwik-deshpande

Add .gitignore

Downgraded globus-compute-endpoint to 2.2.0.
We need to use 2.2.0 in-order to run functions using singularity containers.

Updated example. Created venv installed custom-image-builder directly from the feature branch.
Tested the code end to end.

Unified endpoint, single endpoint for building image and running the custom image.

Documented steps for creation of endpoint in delta and using conda env to manage dependencies.

2023-10-09 19:07 UTC, BenGalewsky commented
Remove the polling in the build_container code.
>         while not fut.done():
>            sleep(30)


`fut.result()` should block on the future completing...

2023-10-09 19:51 UTC, BenGalewsky requested changes

2023-10-09 19:51 UTC, BenGalewsky commented on README.md
> +## Prerequisite.
Put the note about GC Endpoint 2.0 here - to make sure users don't ignore your pin in this example.

2023-10-09 19:51 UTC, BenGalewsky commented on README.md
> +pip install custom-image-builder
Tell me we don't need this!

2023-10-09 19:51 UTC, BenGalewsky commented on README.md
> +            scheduler_mode='soft',
Highlight these three lines in the paragraph. This is the magic that makes it work!

2023-10-09 19:51 UTC, BenGalewsky commented on README.md
> +    example_endpoint = "0b4e042b-edd5-4951-9ce5-6608c2ef6cb8"
This should just be the `image_builder_endpoint` - only one endpoint to rule them all!

2023-10-09 21:54 UTC, ritwik-deshpande commented on README.md
> +    example_endpoint = "0b4e042b-edd5-4951-9ce5-6608c2ef6cb8"
Yes I'll update the README.md

2023-10-09 21:57 UTC, ritwik-deshpande commented on README.md
> +pip install custom-image-builder
Yes I have fixed the issue using from globus_compute_sdk.serialize import DillCodeSource

2023-10-12 20:59 UTC, ritwik-deshpande commented on README.md
> +## Prerequisite.
Yes added it here

2023-10-17 17:17 UTC, BenGalewsky approved these changes
This is good - let's do one final PR with error handling

2023-10-17 17:17 UTC, merged